# path
#path: ./dataset
path: c:/Users/JukkaPelto-aho/DocumentsNotBackedUp/yamk-git/drone-object-detection/dataset
train: images/train  
val: images/val  
test: images/test

# Number of classes
nc: 6

# Class names
names:
  - motor_boat
  - sailing_boat
  - ship
  - sea_mark
  - floating_object
  - dock